### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by someguynamedmatt** [someguynamedmatt/snif#2]
- [ ] Introduce `clap-rs` to project

- [ ] More detailed packet output

- [ ] CL arg to enable/disable packet output
